version: '3.8'

services:
  backend:
    image: hunlam03/mern-backend:1.0
    network_mode: "host"
    environment:
      - PORT=5000
      - MONGO_URI=mongodb://0947555814cc_db_user:lamhung3001@ac-1ny5g9j-shard-00-00.9wl2yip.mongodb.net:27017,ac-1ny5g9j-shard-00-01.9wl2yip.mongodb.net:27017,ac-1ny5g9j-shard-00-02.9wl2yip.mongodb.net:27017/cloud_lab?ssl=true&replicaSet=atlas-wmreoa-shard-0&authSource=admin&appName=Cluster0&tlsAllowInvalidCertificates=true
      - MONGODB_URI=mongodb://0947555814cc_db_user:lamhung3001@ac-1ny5g9j-shard-00-00.9wl2yip.mongodb.net:27017,ac-1ny5g9j-shard-00-01.9wl2yip.mongodb.net:27017,ac-1ny5g9j-shard-00-02.9wl2yip.mongodb.net:27017/cloud_lab?ssl=true&replicaSet=atlas-wmreoa-shard-0&authSource=admin&appName=Cluster0&tlsAllowInvalidCertificates=true

  frontend:
    image: hunlam03/mern-frontend:1.0
    ports:
      - "3000:3000"
    volumes:
      - ./mern-demo/client/src:/app/src
